/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_hyperledger_besu_nativelib_constantine_LibConstantineEIP196 */

#ifndef _Included_org_hyperledger_besu_nativelib_constantine_LibConstantineEIP196
#define _Included_org_hyperledger_besu_nativelib_constantine_LibConstantineEIP196
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_hyperledger_besu_nativelib_constantine_LibConstantineEIP196
 * Method:    ctt_eth_evm_bn254_g1add
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_org_hyperledger_besu_nativelib_constantine_LibConstantineEIP196_ctt_1eth_1evm_1bn254_1g1add
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_hyperledger_besu_nativelib_constantine_LibConstantineEIP196
 * Method:    ctt_eth_evm_bn254_g1mul
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_org_hyperledger_besu_nativelib_constantine_LibConstantineEIP196_ctt_1eth_1evm_1bn254_1g1mul
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_hyperledger_besu_nativelib_constantine_LibConstantineEIP196
 * Method:    ctt_eth_evm_bn254_pairingCheck
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_org_hyperledger_besu_nativelib_constantine_LibConstantineEIP196_ctt_1eth_1evm_1bn254_1pairingCheck
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
